# -*- coding: utf-8 -*-
"""bert_sentiment_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_c7T09g_DMw0lvNazlIVDRySsjl6s--
"""

!pip install transformers datasets scikit-learn

import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset
from sklearn.metrics import accuracy_score, f1_score

dataset = load_dataset("imdb")  # Download IMDB dataset
train_dataset = dataset["train"]
test_dataset = dataset["test"]

print(train_dataset[0])  # See one example

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize(batch):
    return tokenizer(batch['text'], padding=True, truncation=True, max_length=128)

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# Format for PyTorch
train_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])
test_dataset.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='weighted')
    return {'accuracy': acc, 'f1': f1}

training_args = TrainingArguments(
    output_dir='./results',         # Save model here
    num_train_epochs=2,             # You can increase to 3-4 if GPU available
    per_device_train_batch_size=16, # Depends on GPU memory
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',           # Reverting to logging_dir to fix TypeError
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True
)

train_dataset_small = train_dataset.select(range(2000))
test_dataset_small = test_dataset.select(range(500))

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_small,
    eval_dataset=test_dataset_small,
    compute_metrics=compute_metrics
)

results = trainer.evaluate()
print(results)

model.save_pretrained("./bert_sentiment_model")
tokenizer.save_pretrained("./bert_sentiment_model")

from transformers import pipeline

# Load the saved model
classifier = pipeline(
    "sentiment-analysis",
    model="./bert_sentiment_model",
    tokenizer="./bert_sentiment_model"
)

# Test a sample
sample_text = "I absolutely loved this movie!"
result = classifier(sample_text)
print(result)

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from transformers import pipeline
# 
# st.title("BERT Sentiment Classifier Demo")
# 
# # Load your saved model
# classifier = pipeline("sentiment-analysis", model="./bert_sentiment_model", tokenizer="./bert_sentiment_model")
# 
# # Input box for text
# text = st.text_area("Enter text here:")
# 
# # Predict button
# if st.button("Predict"):
#     result = classifier(text)
#     st.write(result)

!pip install gradio --quiet

import gradio as gr
from transformers import pipeline

# Load your trained model
classifier = pipeline("sentiment-analysis", model="./bert_sentiment_model", tokenizer="./bert_sentiment_model")

# Function to predict sentiment
def predict_sentiment(text):
    result = classifier(text)[0]  # returns a list with dict
    return f"Label: {result['label']}, Score: {result['score']:.3f}"

# Create Gradio interface
demo = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(lines=3, placeholder="Enter text here..."),
    outputs="text",
    title="BERT Sentiment Classifier Demo"
)

# Launch demo with public URL
demo.launch(share=True)

model.save_pretrained("bert_sentiment_model")
tokenizer.save_pretrained("bert_sentiment_model")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import gradio as gr
# from transformers import BertTokenizer, BertForSequenceClassification
# import torch
# 
# model = BertForSequenceClassification.from_pretrained("bert_sentiment_model")
# tokenizer = BertTokenizer.from_pretrained("bert_sentiment_model")
# 
# def predict(text):
#     inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
#     outputs = model(**inputs)
#     prediction = torch.argmax(outputs.logits, dim=1).item()
#     return "Positive" if prediction == 1 else "Negative"
# 
# iface = gr.Interface(
#     fn=predict,
#     inputs="text",
#     outputs="text",
#     title="BERT Sentiment Analysis"
# )
# 
# if __name__ == "__main__":
#     iface.launch()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# transformers
# torch
# gradio

!pip install -q huggingface_hub gradio

from huggingface_hub import login
login()

!gradio deploy